### PR TITLE
Combine save and evaluate

### LINKED ISSUE #92: Evaluate answer not available without save
When filling in answers in the comparison view, one has to first save the answers, and then in a seperate action evaluate the answers to view the results. More intuitively would be to evaluate and save in one action.
Users will now have to go through more stages:
`home -> [compare] -> questions -> [save] -> [evaluate] -> comparison`
I'd like to move towards:
`home -> [compare] -> questions -> [evaluate] -> comparison`

### PR DESCRIPTION
**Pull request by andreabettich**
Still needs some work. 

PR will resolve #92

### CODE REVIEW

**Comment by nicorikken** [comment]
Going by the code, it seems to make sense. What needs some more work?

**Comment by andreabettich** [comment]
The values are not stored and when you switched back you had the default values in the selection.

**Comment by nicorikken** [comment]
Ah right, so the set_cookie should be included in all output. I can give that a try. Would be nice!
Easier to observe with the witespace enabled:
https://github.com/freedomvote/freedomvote/pull/97/files?w=1

**Comment by andreabettich** [comment]
image

**Comment by andreabettich** [comment]
Should now work as expected.

**Comment by nicorikken** [comment]
Looks good, I can understand the changes in retrospect. I'll go ahead and deploy this fix. Thanks!

**Comment by nicorikken** [comment]
Can I merge this one?

**Comment by andreabettich** [comment]
Yes, you can merge this change. Should work :)

**Pull request merged**
